[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://lwflptiltwnxjvfvtyrx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZmxwdGlsdHdueGp2ZnZ0eXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDQ2MDQsImV4cCI6MjA2NTM4MDYwNH0.X_2LK7DBqAePQ5d-1SQ0fijAedMgPlTjoN1zekn5fmg"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = "https://lwflptiltwnxjvfvtyrx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZmxwdGlsdHdueGp2ZnZ0eXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDQ2MDQsImV4cCI6MjA2NTM4MDYwNH0.X_2LK7DBqAePQ5d-1SQ0fijAedMgPlTjoN1zekn5fmg"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "https://lwflptiltwnxjvfvtyrx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZmxwdGlsdHdueGp2ZnZ0eXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDQ2MDQsImV4cCI6MjA2NTM4MDYwNH0.X_2LK7DBqAePQ5d-1SQ0fijAedMgPlTjoN1zekn5fmg"

[context.branch-deploy.environment]
  VITE_SUPABASE_URL = "https://lwflptiltwnxjvfvtyrx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZmxwdGlsdHdueGp2ZnZ0eXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDQ2MDQsImV4cCI6MjA2NTM4MDYwNH0.X_2LK7DBqAePQ5d-1SQ0fijAedMgPlTjoN1zekn5fmg"